# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/FILE/FPGA/ZYNQ/PCIe/CH01_AXI_DMA_LOOP/CH01_AXI_DMA_LOOP/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_auto_pc_1/system_auto_pc_1.xci
# IP: The module: 'system_auto_pc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/FILE/FPGA/ZYNQ/PCIe/CH01_AXI_DMA_LOOP/CH01_AXI_DMA_LOOP/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_auto_pc_1/system_auto_pc_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_auto_pc_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: f:/FILE/FPGA/ZYNQ/PCIe/CH01_AXI_DMA_LOOP/CH01_AXI_DMA_LOOP/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_auto_pc_1/system_auto_pc_1.xci
# IP: The module: 'system_auto_pc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/FILE/FPGA/ZYNQ/PCIe/CH01_AXI_DMA_LOOP/CH01_AXI_DMA_LOOP/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_auto_pc_1/system_auto_pc_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_auto_pc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
